// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bacwvumjkbpuqrvhignp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhY3d2dW1qa2JwdXFydmhpZ25wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1ODk0MTMsImV4cCI6MjA1OTE2NTQxM30.Z_uOuESGv0DYOBGViwm2iQpPLd8OIBfK5dMwOr1pfY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);